### ISSUE TITLE
Match the whole word only

### ISSUE THREAD

**Issue by SamiSammour** [haoxins/keyword-filter#10]
Hi,
Is there a way in which I can specify some options for my search? like I want to match whole word only, or I want to match case and so on...

**Comment by coderhaoxin** [comment]
Show me an example?

**Comment by SamiSammour** [comment]
I have a list of words I want to check if they exist in an article but the problem is that I get irrelevant result because the search is on the word whenever it is.
for example one of the words is Oman, now whenever the word "woman", "roman", "romance" occurs it is matched to the word "Oman" which is wrong for my case.
